#ifndef TOSSICAT_H
#define TOSSICAT_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#ifdef _WIN32
#  ifdef TOSSICAT_EXPORTS
#    define TOSSICAT_API __declspec(dllexport)
#  else
#    define TOSSICAT_API __declspec(dllimport)
#  endif
#else
#  define TOSSICAT_API
#endif


/**
 * ## 마지막 에러 메시지를 반환하는 함수
 *
 * 에러가 없으면 빈 문자열을 반환합니다.
 * 반환된 포인터는 다음 tossicat 함수 호출 전까지만 유효합니다.
 * `tossicat_free()`로 해제하지 마세요.
 *
 * ### 사용 예시 (C)
 * ```c
 * char* result = tossicat_postfix(word, tossi);
 * if (!result) {
 *     const char* err = tossicat_last_error();
 *     printf("에러: %s\n", err);
 * }
 * ```
 */
TOSSICAT_API const char *tossicat_last_error(void);

/**
 * ## 입력된 토시를 단어에 맞게 변환해, 단어와 합쳐 반환하는 함수
 *
 * C에서 사용하는 `postfix()` 함수입니다.
 * 반환된 문자열은 반드시 `tossicat_free()`로 해제해야 합니다.
 *
 * ### 매개변수
 * - `word`: 토시를 붙일 단어 (UTF-8 인코딩 C 문자열)
 * - `tossi`: 붙일 토시 (UTF-8 인코딩 C 문자열)
 *
 * ### 반환값
 * - 성공: 변환된 문자열 (단어 + 변환된 토시)
 * - 실패: NULL (`tossicat_last_error()`로 원인 조회)
 *
 * ### 사용 예시 (C)
 * ```c
 * char* result = tossicat_postfix("검", "을");
 * // result: "검을"
 * tossicat_free(result);
 *
 * char* result2 = tossicat_postfix("포션", "을");
 * // result2: "포션을"
 * tossicat_free(result2);
 * ```
 */
TOSSICAT_API char *tossicat_postfix(const char *word, const char *tossi);

/**
 * ## 변경할 토시가 여러 개 들어 있는 문장을 적절한 토시로 변경하는 함수
 *
 * C에서 사용하는 `modify_sentence()` 함수입니다.
 * 반환된 문자열은 반드시 `tossicat_free()`로 해제해야 합니다.
 *
 * ### 매개변수
 * - `sentence`: 변환할 문장 (UTF-8 인코딩 C 문자열)
 *   - 형식: `"{단어, 토시} 문장"`
 *
 * ### 반환값
 * - 성공: 변환된 문장
 * - 실패: NULL (`tossicat_last_error()`로 원인 조회)
 *
 * ### 사용 예시 (C)
 * ```c
 * char* result = tossicat_modify_sentence(
 *     "{철수, 은} {영희, 과} {밥, 를} 먹습니다."
 * );
 * // result: "철수는 영희와 밥을 먹습니다."
 * tossicat_free(result);
 * ```
 */
TOSSICAT_API char *tossicat_modify_sentence(const char *sentence);

/**
 * ## 입력된 문자열에서 마지막 글자의 종성을 반환하는 함수
 *
 * ### 매개변수
 * - `word`: 분석할 단어 (UTF-8 인코딩 C 문자열)
 *
 * ### 반환값
 * - 종성이 있는 경우: 해당 종성의 UTF-8 인코딩 문자열
 * - 종성이 없는 경우: " " (공백)
 * - 한글이 아닌 경우: "N"
 * - 실패: NULL (`tossicat_last_error()`로 원인 조회)
 *
 * 반환된 문자열은 반드시 `tossicat_free()`로 해제해야 합니다.
 */
TOSSICAT_API char *tossicat_guess_final_letter(const char *word);

/**
 * ## tossicat 함수들이 반환한 문자열을 해제하는 함수
 *
 * `tossicat_postfix()`, `tossicat_modify_sentence()`,
 * `tossicat_guess_final_letter()`가 반환한 문자열을
 * 이 함수로 반드시 해제해야 합니다.
 *
 * ### 매개변수
 * - `s`: 해제할 문자열 포인터. NULL이면 무시합니다.
 *
 * ### 사용 예시 (C)
 * ```c
 * char* result = tossicat_postfix("검", "을");
 * printf("%s\n", result);
 * tossicat_free(result);  // 반드시 해제
 * ```
 */
TOSSICAT_API void tossicat_free(char *s);

#endif  /* TOSSICAT_H */
